### ISSUE TITLE
Unable to integrate with Report portal.

### ISSUE THREAD

**Issue by anooppc07** [healenium/healenium-plugin-reportportal#5]
When trying to build the project after cloning the below error is displayed
"Could not find com.github.reportportal:commons-dao:7ff31473."

Also if try to use the Jar from releases and upload to portal the plugin integration is not getting listed..

Can you please do the needful.

**Comment by HealeniumIntegrate** [comment]
Hi
i am getting below  error, can u help me here

![image](https://user-images.githubusercontent.com/128289619/226170330-cb9665ff-e0ba-4066-86a2-1aad5fd5b344.png)
* Where:
Build file 'C:\Users\Admin\IdeaProjects\Heal\healenium-plugin-reportportal\build.gradle' line: 109

* What went wrong:
A problem occurred evaluating root project 'healenium-plugin-reportportal'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.reportportal:commons-dao:7ff31473.
     Required by:
         project :
   > Could not find com.github.reportportal:commons-dao:7ff31473.
     Required by:
         project : > com.github.reportportal:plugin-api:48e08b04

**Comment by Alex-Reif** [comment]
Fixed v. 2.0.0
